# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
#    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
      args: ["--unsafe"]
    - id: check-added-large-files
- repo: local
  hooks:
    - id: verify-commit-message
      name: Verify commit message format
      entry: python -m infra.git_hooks.verify_commit_message
      language: python
      verbose: true
      stages: [commit-msg]
## Using this mirror lets us use mypyc-compiled black, which is about 2x faster
#- repo: https://github.com/psf/black-pre-commit-mirror
#  rev: 23.10.1
#  hooks:
#    - id: black
#      language_version: python3
# - repo: https://github.com/pre-commit/mirrors-clang-format
#   rev: v18.1.5
#   hooks:
#     - id: clang-format
#       types_or: [c++, c]
